version: '3'
services:
  app:
    container_name: dpm_php
    build:
      context: ./php
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    container_name: dpm_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=${DB_NAME:-docker_db}
      - MYSQL_USER=${DB_USER:-docker_user}
      - MYSQL_PASSWORD=${DB_PASS:-docker_pass}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-docker_pass}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
